Add CI to backend with Gitgub Actions
vorobeybird/Sobesity-BE pull request #3
Opened 2023-02-03 10:17 UTC by devdeM1

2023-02-03 10:36 UTC, Andmedoctopus commented
Great
1. Add people to reviewers
1. Add .idea folder to `.gitignore`

2023-02-03 10:36 UTC, Andmedoctopus commented on .github/workflows/test_on_push.yml
> +    - uses: actions/checkout@master
why master? Could you try to "fail" the CI

2023-02-03 10:54 UTC, Andmedoctopus requested changes
remove .idea folder

2023-02-03 11:15 UTC, Andmedoctopus commented on .github/workflows/test_on_push.yml
> +    - uses: actions/checkout@master
Should works fine. It's probably version of actions

2023-02-03 11:40 UTC, Andmedoctopus commented on .github/workflows/tests_on_push.yml
> +    - uses: actions/checkout@CI
It doesn't work with `CI`

the branch name is the name of the checkout utility not of your branch. Just revert to master.

2023-02-03 13:39 UTC, Andmedoctopus approved these changes

2023-02-06 10:04 UTC, vorobeybird approved these changes

2023-02-06 10:45 UTC, Zhental approved these changes

2023-02-06 13:50 UTC, merged