Jwt auth
vorobeybird/Sobesity-BE pull request #4
Opened 2023-02-03 10:48 UTC by Andmedoctopus

2023-02-03 10:49 UTC, Andmedoctopus commented
COOL

2023-02-03 10:50 UTC, Andmedoctopus commented
> COOL

NOT cool

2023-02-03 10:51 UTC, Andmedoctopus commented on src/sobesity/jwt.py
> +        breakpoint()
Remove breakpoint

2023-02-03 10:53 UTC, Andmedoctopus commented on src/sobesity/jwt.py
> +    return payload["sub"]
Remove magic string

2023-02-03 10:53 UTC, Andmedoctopus commented on src/sobesity/jwt.py
> +    return jwt.encode({"sub": user_id}, "secret", algorithm="HS256")
Add user jwt struct

2023-02-13 09:07 UTC, Zhental submitted a review, later dismissed

2023-02-13 10:07 UTC, vorobeybird requested changes
Please add current_user endpoint

2023-02-15 19:15 UTC, Andmedoctopus commented
> Please add
> 
>     1. current_user endpoint
> 
>     2. Name and Surname fields to api/user endpoint
>        ![image](https://user-images.githubusercontent.com/46844648/218467233-d130c03c-75fd-4ccb-ad12-b4d26af2cdb0.png)

Added

2023-02-20 10:51 UTC, vorobeybird approved these changes

2023-02-20 11:42 UTC, merged